/** uu.chart.js -- javascript for rendering uu.chart chart types from
  * JSON chart API into jqplot charts.
  */

// global namspaces:
var jq = jQuery; /* alias */

var uu = new Object();      /* namespaces */
uu.chart = new Object();

uu.sorted = function(arr, cmp) {
    /* return a new sorted array from original */
    if (cmp) return arr.slice().sort(cmp);
    return arr.slice().sort();
}

/**  array max/min for any data-type (req. EC5 Array.prototype.reduce)
  *  prefers non-null values over any null values in sequence always
  *  for both max and min.
  */ 
uu.maxcmp = function (a,b) { return ((a && (a>b)) || !b) ? a : b; }
uu.mincmp = function (a,b) { return ((a && (a<b)) || !b) ? a : b; }
uu.max = function(seq) { return seq.reduce(uu.maxcmp); }
uu.min = function(seq) { return seq.reduce(uu.mincmp); }


uu.chart.normalize_series = function(series) {
    var result = new Array();
    for (var i=0; i<series.length; i++) {
        var element = series[i];
        result.push( [Date.parse(element[0]), element[1]] );
    }
    return result;
}

uu.chart.allkeys = function(data) {
    var rset = new Object(); //use object as fake set-of-names type
    if (data.series) {
        for (var i=0; i<data.series.length; i++) {
            var s = data.series[i];
            if (s.data) {
                var skeys = Object.keys(s.data);
                for (var key in s.data) {
                    rset[key] = 1;
                }
            }
        }
    }
    return uu.sorted(Object.keys(rset));
}

uu.chart.seriesdata = function(data) {
    var r = new Array();
    if (data.series) {
        for (var i=0; i<data.series.length; i++) {
            var s_rep = new Array();
            var s = data.series[i];
            if (s.data) {
                var skeys = uu.sorted(Object.keys(s.data));
                for (var j=0; j<skeys.length; j++) {
                    var key = skeys[j];
                    var point = s.data[key];
                    if (data.x_axis_type == 'date') {
                        if (Date.parse(key)) {
                            s_rep.push([Date.parse(key), point.value]);
                        } else {
                            s_rep.push([key, point.value]);
                        }
                    } else {
                        /* named series elements/points for jqplot are Y-value only:
                            * data-labels are autogenerated, usually from value,
                              * except override via series options pointLabels property.
                            * key implied by consistent order, thus this loop always
                              loops through the series in sorted key order.
                            * X-axis ticks are defined globally for the chart, in order.
                         */
                        s_rep.push(point.value);
                    }
                }
            }
            r.push(s_rep);
        }
    }
    return r;
}


uu.chart.range = function(data) {
    /* get range min, max: returns two item array of min, max values */
    var min = null;
    var max = null;
    if (data.series) {
        for (var i=0; i<data.series.length; i++) {
            var s = data.series[i];
            if (s.range_min) { 
                if (!min) {
                    min = s.range_min;
                } else {
                    if (min > s.range_min) min = s.range_min;
                }
            }
            if (s.range_max) {
                if (!max) {
                    max = s.range_max;
                } else {
                    if (max < s.range_max) max = s.range_max;
                }
            }
        }
    }
    return [min, max];
}

uu.chart.series_colors = function(data) {
    var r = jq.jqplot.config.defaultColors.slice(); //copy defaults
    if (data.series) {
        for (var i=0; i<data.series.length; i++) {
            var s = data.series[i];
            if (s.color) {
                r[i] = s.color; //reassign color, overwrite default
            }
        }
    }
    return r;
}

uu.chart.seriesoptions = function(data) {
    var r = new Array();
    if (data.series) {
        for (var i=0; i<data.series.length; i++) {
            var options = new Object();
            var marker_options = new Object();
            var trend_options = {show:false};
            var s = data.series[i];
            if (s.line_width) options.lineWidth = s.line_width;
            //if (s.color) options.lineColor = s.color;
            // note: line color assigned to seriesColors option for chart, 
            // which takes precedence over options.lineColor
            if (s.marker_style) marker_options.style = s.marker_style;
            if (s.marker_color) marker_options.color = s.marker_color;
            options.markerOptions = marker_options;
            if (s.marker_size) marker_options.size = s.marker_size;
            if (s.marker_width) marker_options.lineWidth = s.marker_width;
            if (s.title) options.label = s.title;
            if (s.units) options.label += ' [&thinsp;' + s.units + '&thinsp;]';
            if (s.show_trend == true) {
                trend_options.show = true;
                if (s.title) {
                    trend_options.label = 'Trend: ' + s.title;
                } else {
                    trend_options.label = 'Trend (linear)';
                }
                if (s.trend_width) {
                    trend_options.lineWidth = s.trend_width;
                } else {
                    trend_options.lineWidth = 1;
                }
                if (s.trend_color) {
                    trend_options.color = s.trend_color;
                }
            }
            options.trendline = trend_options;
            options.pointLabels = {formatString: "%.1f", hideZeros:true};
            r.push(options);
        }
    }
    return r;
}

uu.chart.bar_config = function(data) {
    /* fitting algorithm: bars between 5 and 20 pixels wide, computed to fit */
    var r = new Object();
    var chart_width = 600;
    if (data.width) chart_width = data.width;
    r.series_length = 0;
    r.max_points = 0;
    if (data.series) r.series_length = data.series.length;
    r.max_points = uu.max(data.series.map(function(series) {
        return Object.keys(series.data).length;
        }));
    r.width = Math.min(32, Math.max(5, (((chart_width * 0.8) / (r.max_points + 1)) / (r.series_length + 1))));
    return r;
}


uu.chart.runchart_start = function(data) {
    var s;
    var result = data.start; //default is null value...
    if (result) {
        // start date plus some padding (one month earlier) for left-hand
        // side of chart.
        return Date.parse(result.slice(0,10)).add(-1).months();
    }
    if (data.series) {
        for (var i=0; i<data.series.length; i++) {
            s = data.series[i];
            if (s.data) {
                /* min===earliest date from any series excluding null values */
                result = uu.min([result, uu.min(Object.keys(s.data))]);
            }
        }
    }
    if (Date.today) { //date.js installed
        return Date.parse(result.slice(0,10)).add(-1).months();
    }
    return result.slice(0,10); //date, not datetime in ISO8601
}

uu.chart.fillchart = function(divid, data) {
    var legend = {show:false}; //default is none
    var legend_placement = 'outsideGrid';
    var goal_color = "#333333";
    var x_axis = {};
    var y_axis = {};
    var stack = false;
    var series_defaults = {};
    var series_colors = jq.jqplot.config.defaultColors;
    if ((data.chart_type == "bar") || (data.chart_type == "stacked")) {
        var barwidth = uu.chart.bar_config(data).width;
        if (data.chart_type == "stacked") {
            stack = true;
            barwidth = barwidth * data.series.length;
        }
        var series_defaults = {
            renderer : jq.jqplot.BarRenderer,
            rendererOptions : {
                barWidth : barwidth
                }
            };
        }
    series_colors = uu.chart.series_colors(data);
    var line_width = 4;
    var marker_color = null;
    if (data.goal) {
        if (data.goal_color) goal_color = data.goal_color;
        series_defaults.thresholdLines = {lineColor: goal_color, labelColor: goal_color, yValues: [data.goal]};
    }
    if (data.x_axis_type == 'date') {
        x_axis = {renderer:jq.jqplot.DateAxisRenderer, tickInterval:'1 month', min:uu.chart.runchart_start(data), tickRenderer: jq.jqplot.CanvasAxisTickRenderer, tickOptions: { angle:-65, fontSize:'15pt', fontStretch:1.5, fontFamily:'Arial', fontWeight:'bold', enableFontSupport:true, textColor:'#00f'} };
    } else { /* named */
        x_axis.renderer = jq.jqplot.CategoryAxisRenderer;
        //x_axis.ticks = ['groucho','b','c'];
        x_axis.ticks = uu.chart.allkeys(data);
    }
    if (data.legend_location) {
        if (data.legend_placement) {
            legend_placement = data.legend_placement;
        }
        legend = {show:true, location:data.legend_location, placement:legend_placement, marginTop:'2em'};
    }
    if (data.y_label) {
        y_axis.label = data.y_label;
        if (data.units) {
            y_axis.label += ' ( ' + data.units + ' )';
        }
        if (jq.jqplot.CanvasAxisLabelRenderer) {
            y_axis.labelRenderer = jq.jqplot.CanvasAxisLabelRenderer;
            y_axis.labelOptions = { fontFamily:'Helvetica,Arial,Sans Serif', fontSize:'12pt' };
        }
    }
    var range = uu.chart.range(data);
    if (range[0]) { /*min*/
        y_axis.min = range[0];
    }
    if (range[1]) { /*max*/
        y_axis.max = range[1];
    }
    if (data.x_label) {
        x_axis.label = data.x_label;
    }
    jq.jqplot.config.enablePlugins = true;
    jq.jqplot(divid, uu.chart.seriesdata(data), {
        stackSeries: stack,
        axes:{xaxis:x_axis, yaxis:y_axis},
        axesDefaults: {tickOptions: {fontSize:'7pt'}},
        series:uu.chart.seriesoptions(data),
        seriesDefaults: series_defaults,
        legend: legend,
        seriesColors : series_colors
        });
    // finally, adjust label colors to match line colors using CSS/jQuery:
    for (var i=0; i<series_colors.length; i++) {
        var labelselect = '#' + divid + ' .jqplot-series-' + i + '.jqplot-point-label';
        var points = jq(labelselect);
        for (var j=0; j<points.length; j++) {
            point = jq(points[j]);
            if (data.chart_type == "stacked") {
                v = parseInt(point.html());
                if (v < 20) {
                    point.css('margin-left', '2.2em');
                }
                point.css('backgroundColor', series_colors[i]);
                point.css('padding', '0 0.2em');
                point.css('margin-top', '3em');
            } else {
                point.css('color', series_colors[i]);
            }
        }
    }
}

uu.chart.loadcharts = function() {
    jq('.chartdiv').each(function(index) {
        var div = jq(this);
        var json_url = jq('a[type="application/json"]', div).attr('href');
        var divid = div.attr('id'); 
        jq.ajax({
            url: json_url,
            success: function(responseText) { /*callback*/
                uu.chart.fillchart(divid, responseText);
            }
        });
    });
}


jq('document').ready(function(){
    uu.chart.loadcharts();
});

